var namespace_file_f_s_1_1_data_access_1_1_repositories_1_1_abstractions =
[
    [ "IDirectoryRepository", "interface_file_f_s_1_1_data_access_1_1_repositories_1_1_abstractions_1_1_i_directory_repository.html", "interface_file_f_s_1_1_data_access_1_1_repositories_1_1_abstractions_1_1_i_directory_repository" ],
    [ "IEntryDescriptorRepository", "interface_file_f_s_1_1_data_access_1_1_repositories_1_1_abstractions_1_1_i_entry_descriptor_repository.html", "interface_file_f_s_1_1_data_access_1_1_repositories_1_1_abstractions_1_1_i_entry_descriptor_repository" ],
    [ "IEntryRepository", "interface_file_f_s_1_1_data_access_1_1_repositories_1_1_abstractions_1_1_i_entry_repository.html", "interface_file_f_s_1_1_data_access_1_1_repositories_1_1_abstractions_1_1_i_entry_repository" ],
    [ "IFileRepository", "interface_file_f_s_1_1_data_access_1_1_repositories_1_1_abstractions_1_1_i_file_repository.html", "interface_file_f_s_1_1_data_access_1_1_repositories_1_1_abstractions_1_1_i_file_repository" ]
];