var namespace_file_f_s_1_1_client_1_1_transactions_1_1_abstractions =
[
    [ "ITransactionWrapper", "interface_file_f_s_1_1_client_1_1_transactions_1_1_abstractions_1_1_i_transaction_wrapper.html", "interface_file_f_s_1_1_client_1_1_transactions_1_1_abstractions_1_1_i_transaction_wrapper" ]
];